Pantarei/Bundle/Oauth2Bundle: Code Class Reference
Code Class Reference
Public Member Functions
__construct ($entityPersister, $identifier)
__load ()
__isInitialized ()
getId ()
setCode ($code)
getCode ()
setClientId ($client_id)
getClientId ()
setUsername ($username)
getUsername ()
setRedirectUri ($redirect_uri)
getRedirectUri ()
setExpires ($expires)
getExpires ()
setScope ($scope)
getScope ()
__sleep ()
__clone ()
Public Member Functions inherited from Code
getId ()
Public Member Functions inherited from Code
setCode ($code)
getCode ()
setClientId ($client_id)
getClientId ()
setUsername ($username)
getUsername ()
setRedirectUri ($redirect_uri)
getRedirectUri ()
setExpires ($expires)
getExpires ()
setScope ($scope)
getScope ()
__construct ()
Public Attributes
$__isInitialized__ = false
Private Attributes
$_entityPersister
$_identifier
Additional Inherited Members
Protected Attributes inherited from Code
$id
Detailed Description
THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
Definition at line 8 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
Constructor & Destructor Documentation
__construct ($entityPersister, $identifier)
Definition at line 13 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
Member Function Documentation
__clone ()
Definition at line 132 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
__isInitialized ()
Definition at line 39 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\$__isInitialized__.
__load ()
Definition at line 19 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
Referenced by Code\getClientId(), Code\getCode(), Code\getExpires(), Code\getId(), Code\getRedirectUri(), Code\getScope(), Code\getUsername(), Code\setClientId(), Code\setCode(), Code\setExpires(), Code\setRedirectUri(), Code\setScope(), and Code\setUsername().
__sleep ()
Definition at line 127 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
getClientId ()
Definition at line 72 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\__load().
getCode ()
Definition at line 60 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\__load().
getExpires ()
Definition at line 108 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\__load().
getId ()
Definition at line 45 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\__load().
getRedirectUri ()
Definition at line 96 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\__load().
getScope ()
Definition at line 120 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\__load().
getUsername ()
Definition at line 84 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\__load().
setClientId ($client_id)
Definition at line 66 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\$client_id, and Code\__load().
setCode ($code)
Definition at line 54 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\$code, and Code\__load().
setExpires ($expires)
Definition at line 102 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\$expires, and Code\__load().
setRedirectUri ($redirect_uri)
Definition at line 90 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\$redirect_uri, and Code\__load().
setScope ($scope)
Definition at line 114 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\$scope, and Code\__load().
setUsername ($username)
Definition at line 78 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
References Code\$username, and Code\__load().
Member Data Documentation
$__isInitialized__ = false
Definition at line 12 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
Referenced by Code\__isInitialized().
$_entityPersister private
Definition at line 10 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
$_identifier private
Definition at line 11 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php.
The documentation for this class was generated from the following file:
Tests/app/cache/dev/doctrine/orm/Proxies/__CG__PantareiBundleOauth2BundleTestsTestBundleEntityCode.php