Pantarei/Bundle/Oauth2Bundle: AccessToken Class Reference
AccessToken Class Reference
Public Member Functions
__construct ($entityPersister, $identifier)
__load ()
__isInitialized ()
getId ()
setAccessToken ($access_token)
getAccessToken ()
setTokenType ($token_type)
getTokenType ()
setClientId ($client_id)
getClientId ()
setUsername ($username)
getUsername ()
setExpires ($expires)
getExpires ()
setScope ($scope)
getScope ()
__sleep ()
__clone ()
Public Attributes
$__isInitialized__ = false
Private Attributes
$_entityPersister
$_identifier
Additional Inherited Members
Protected Attributes inherited from AccessToken
$id
$access_token
$token_type
$client_id
$username
$expires
$scope
Detailed Description
THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
Definition at line 8 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
Constructor & Destructor Documentation
__construct ($entityPersister, $identifier)
Definition at line 13 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
Member Function Documentation
__clone ()
Definition at line 132 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
__isInitialized ()
Definition at line 39 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\$__isInitialized__.
__load ()
Definition at line 19 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
Referenced by AccessToken\getAccessToken(), AccessToken\getClientId(), AccessToken\getExpires(), AccessToken\getId(), AccessToken\getScope(), AccessToken\getTokenType(), AccessToken\getUsername(), AccessToken\setAccessToken(), AccessToken\setClientId(), AccessToken\setExpires(), AccessToken\setScope(), AccessToken\setTokenType(), and AccessToken\setUsername().
__sleep ()
Definition at line 127 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
getAccessToken ()
Definition at line 60 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\__load().
getClientId ()
Definition at line 84 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\__load().
getExpires ()
Definition at line 108 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\__load().
getId ()
Definition at line 45 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\__load().
getScope ()
Definition at line 120 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\__load().
getTokenType ()
Definition at line 72 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\__load().
getUsername ()
Definition at line 96 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\__load().
setAccessToken ($access_token)
Definition at line 54 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\$access_token, and AccessToken\__load().
setClientId ($client_id)
Definition at line 78 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\$client_id, and AccessToken\__load().
setExpires ($expires)
Definition at line 102 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\$expires, and AccessToken\__load().
setScope ($scope)
Definition at line 114 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\$scope, and AccessToken\__load().
setTokenType ($token_type)
Definition at line 66 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\$token_type, and AccessToken\__load().
setUsername ($username)
Definition at line 90 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
References AccessToken\$username, and AccessToken\__load().
Member Data Documentation
$__isInitialized__ = false
Definition at line 12 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
Referenced by AccessToken\__isInitialized().
$_entityPersister private
Definition at line 10 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
$_identifier private
Definition at line 11 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php.
The documentation for this class was generated from the following file:
Tests/app/cache/test/doctrine/orm/Proxies/__CG__PantareiBundleOauth2BundleTestsTestBundleEntityAccessToken.php