Pantarei/Bundle/Oauth2Bundle: Client Class Reference
Client Class Reference
Public Member Functions
__construct ($entityPersister, $identifier)
__load ()
__isInitialized ()
getId ()
setClientId ($client_id)
getClientId ()
setClientSecret ($client_secret)
getClientSecret ()
setRedirectUri ($redirect_uri)
getRedirectUri ()
__sleep ()
__clone ()
__construct ($entityPersister, $identifier)
__load ()
__isInitialized ()
getId ()
setClientId ($client_id)
getClientId ()
setClientSecret ($client_secret)
getClientSecret ()
setRedirectUri ($redirect_uri)
getRedirectUri ()
__sleep ()
__clone ()
Public Attributes
$__isInitialized__ = false
Private Attributes
$_entityPersister
$_identifier
Additional Inherited Members
Protected Attributes inherited from Client
$id
$client_id
$client_secret
$redirect_uri
Detailed Description
THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
Definition at line 8 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
Constructor & Destructor Documentation
__construct ($entityPersister, $identifier)
Definition at line 13 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
__construct ($entityPersister, $identifier)
Definition at line 13 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
Member Function Documentation
__clone ()
Definition at line 96 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
__clone ()
Definition at line 96 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
__isInitialized ()
Definition at line 39 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\$__isInitialized__.
__isInitialized ()
Definition at line 39 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\$__isInitialized__.
__load ()
Definition at line 19 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
Referenced by Client\getClientId(), Client\getClientSecret(), Client\getId(), Client\getRedirectUri(), Client\setClientId(), Client\setClientSecret(), and Client\setRedirectUri().
__load ()
Definition at line 19 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
__sleep ()
Definition at line 91 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
__sleep ()
Definition at line 91 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
getClientId ()
Definition at line 60 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
getClientId ()
Definition at line 60 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
getClientSecret ()
Definition at line 72 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
getClientSecret ()
Definition at line 72 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
getId ()
Definition at line 45 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
getId ()
Definition at line 45 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
getRedirectUri ()
Definition at line 84 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
getRedirectUri ()
Definition at line 84 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\__load().
setClientId ($client_id)
Definition at line 54 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\$client_id, and Client\__load().
setClientId ($client_id)
Definition at line 54 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\$client_id, and Client\__load().
setClientSecret ($client_secret)
Definition at line 66 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\$client_secret, and Client\__load().
setClientSecret ($client_secret)
Definition at line 66 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\$client_secret, and Client\__load().
setRedirectUri ($redirect_uri)
Definition at line 78 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
References Client\$redirect_uri, and Client\__load().
setRedirectUri ($redirect_uri)
Definition at line 78 of file __CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php.
References Client\$redirect_uri, and Client\__load().
Member Data Documentation
$__isInitialized__ = false
Definition at line 12 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
Referenced by Client\__isInitialized().
$_entityPersister private
Definition at line 10 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
$_identifier private
Definition at line 11 of file __CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php.
The documentation for this class was generated from the following files:
Tests/app/cache/test/doctrine/orm/Proxies/__CG__PantaReiBundleOAuth2BundleTestsTestBundleEntityClient.php
Tests/app/cache/test/doctrine/orm/Proxies/__CG__PantareiBundleOauth2BundleTestsTestBundleEntityClient.php