Pantarei/Bundle/Oauth2Bundle: UserManager Class Reference
UserManager Class Reference
Public Member Functions
getClass ()
createUser ()
deleteUser (UserInterface $user)
reloadUser (UserInterface $user)
updateUser (UserInterface $user)
loadUserByUsername ($username)
refreshUser (UserInterface $user)
supportsClass ($class)
Detailed Description
UserManager
This class was generated by the Doctrine ORM. Add your own custom repository methods below.
Definition at line 27 of file UserManager.php.
Member Function Documentation
createUser ()
Definition at line 34 of file UserManager.php.
References UserManager\getClass().
deleteUser (UserInterface $user)
Definition at line 40 of file UserManager.php.
getClass ()
Definition at line 29 of file UserManager.php.
Referenced by UserManager\createUser().
loadUserByUsername ($username)
Definition at line 57 of file UserManager.php.
refreshUser (UserInterface $user)
Definition at line 69 of file UserManager.php.
References UserManager\supportsClass().
reloadUser (UserInterface $user)
Definition at line 46 of file UserManager.php.
supportsClass ($class)
Definition at line 79 of file UserManager.php.
Referenced by UserManager\refreshUser().
updateUser (UserInterface $user)
Definition at line 51 of file UserManager.php.
The documentation for this class was generated from the following file:
Tests/TestBundle/Entity/UserManager.php